apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: allure-pipeline-
  namespace: tekton-allure
spec:
  serviceAccountName: tekton-pipeline-sa
  pipelineRef:
    name: allure-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
    - name: APPLICATION_NAME
      value: "allure-sample"
    - name: GIT_URL
      value: "https://github.com/t-matsu200/allure-sample.git"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: allure-sample
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 500Mi
